MedialCare/MedialCare/Models/Data/Entities/PolicyOnEmployee.cs
using MedialCare.Models.Enum;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace MedialCare.Models.Entities
{
    public class PolicyOnEmployee
    {
        [Key]
        public int ID { get; set; }

        [ForeignKey("User")]
        [Display(Name = "Name User")]
        public int UserId{ get; set; }

        [ForeignKey("Policy")]
        [Display(Name = "Name Policy")]
        public int PolicyId { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }

        [EnumDataType(typeof(Status))]
        public Status Status { get; set; }
        public DateTime CreatedAt { get; set; }
        public string CreatedBy { get; set; }

        public DateTime UpdatedAt { get; set; }

        public string UpdatedBy { get; set; }

        public string Version { get; set; }

        public bool Deleted { get; set; }
        public User User { get; set; }
        public Policy Policy  { get; set; }
    }
}

MedialCare/MedialCare/Areas/Admin/Controllers/PolicyOnEmployeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MedialCare.Models.EF;
using MedialCare.Models.Entities;
using MedialCare.Models.Catalog;
using MedialCare.Areas.Account.Controllers;

namespace MedialCare.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class PolicyOnEmployeesController : CheckAccountController
    {
        private readonly ApplicationDbContext _context;
        public int PageSize = 5;

        public PolicyOnEmployeesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Admin/PolicyOnEmployees
        public async Task<IActionResult> Index( int page = 1)
        {
            var query = from e in _context.PolicyOnEmployees select new { e };
            var info = new ListViewModel
            {
                PolicyOnEmployee = await query.Select(x => new PolicyOnEmployee
                {
                    ID = x.e.ID,
                    StartDate = x.e.StartDate,
                    EndDate = x.e.EndDate,
                    Status = x.e.Status,
                    Policy = x.e.Policy,
                    User=x.e.User,
                }).OrderBy(x => x.ID)
                .Skip((page - 1) * PageSize).Take(PageSize).ToListAsync(),
                PagingModel = new PagingModel
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = _context.Policys.Count()
                }
            };
            return View(info);
        }

        // GET: Admin/PolicyOnEmployees/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var policyOnEmployee = await _context.PolicyOnEmployees
                .Include(p => p.Policy)
                .Include(p => p.User)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (policyOnEmployee == null)
            {
                return NotFound();
            }

            return View(policyOnEmployee);
        }

        // GET: Admin/PolicyOnEmployees/Create
        public IActionResult Create()
        {
            ViewData["PolicyName"] = new SelectList(_context.Policys, "ID", "Name");
            ViewData["PolicyAmount"] = new SelectList(_context.Policys, "ID", "Amount");
            ViewData["Username"] = new SelectList(_context.Users, "ID", "Username");
            return View();
        }

        // POST: Admin/PolicyOnEmployees/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,UserId,PolicyId,StartDate,EndDate,Status,CreatedAt,CreatedBy,UpdatedAt,UpdatedBy,Version,Deleted")] PolicyOnEmployee policyOnEmployee)
        {
            if (ModelState.IsValid)
            {
                _context.Add(policyOnEmployee);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["PolicyName"] = new SelectList(_context.Policys, "ID", "Name", policyOnEmployee.PolicyId);
            ViewData["PolicyAmount"] = new SelectList(_context.Policys, "ID", "Amount", policyOnEmployee.PolicyId);
            ViewData["Username"] = new SelectList(_context.Users, "ID", "Username", policyOnEmployee.UserId);
            return View(policyOnEmployee);
        }

        // GET: Admin/PolicyOnEmployees/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var policyOnEmployee = await _context.PolicyOnEmployees.FindAsync(id);
            if (policyOnEmployee == null)
            {
                return NotFound();
            }
            ViewData["PolicyName"] = new SelectList(_context.Policys, "ID", "Name", policyOnEmployee.PolicyId);
            ViewData["PolicyAmount"] = new SelectList(_context.Policys, "ID", "Amount", policyOnEmployee.PolicyId);
            ViewData["UserName"] = new SelectList(_context.Users, "ID", "Username", policyOnEmployee.UserId);
            return View(policyOnEmployee);
        }

        // POST: Admin/PolicyOnEmployees/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,UserId,PolicyId,StartDate,EndDate,Status,CreatedAt,CreatedBy,UpdatedAt,UpdatedBy,Version,Deleted")] PolicyOnEmployee policyOnEmployee)
        {
            if (id != policyOnEmployee.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(policyOnEmployee);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PolicyOnEmployeeExists(policyOnEmployee.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["PolicyName"] = new SelectList(_context.Policys, "ID", "Name", policyOnEmployee.PolicyId);
            ViewData["PolicyAmount"] = new SelectList(_context.Policys, "ID", "Amount", policyOnEmployee.PolicyId);
            ViewData["UserId"] = new SelectList(_context.Users, "ID", "Username", policyOnEmployee.UserId);
            return View(policyOnEmployee);
        }

        // GET: Admin/PolicyOnEmployees/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var policyOnEmployee = await _context.PolicyOnEmployees
                .Include(p => p.Policy)
                .Include(p => p.User)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (policyOnEmployee == null)
            {
                return NotFound();
            }

            return View(policyOnEmployee);
        }

        // POST: Admin/PolicyOnEmployees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var policyOnEmployee = await _context.PolicyOnEmployees.FindAsync(id);
            _context.PolicyOnEmployees.Remove(policyOnEmployee);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PolicyOnEmployeeExists(int id)
        {
            return _context.PolicyOnEmployees.Any(e => e.ID == id);
        }
    }
}

MedialCare/MedialCare/Areas/Admin/Views/PolicyOnEmployees/Create.cshtml
@model PolicyOnEmployee

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="card-box">
    <h4 class="m-2">Policy</h4>
    <div style="padding:30px">
        <div class="row">
            <div class="col">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <div class="form-group">
                            <div class="form-group row">
                                <div class="col-4">
                                    <label asp-for="UserId" class="control-label"></label>
                                </div>
                                <div class="col-6">
                                    <select asp-for="UserId" class="form-control" asp-items="ViewBag.Username"></select>
                                </div>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-4">
                                <label asp-for="PolicyId" class="control-label"></label>
                            </div>
                            <div class="col-6">
                                <select asp-for="PolicyId" class="form-control" asp-items="ViewBag.PolicyName"></select>
                            </div>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-4">
                            <label asp-for="StartDate" class="control-label"></label>
                        </div>
                        <div class="col-6">
                            <input asp-for="StartDate" class="form-control" />
                            <span asp-validation-for="StartDate" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-4">
                            <label asp-for="EndDate" class="control-label"></label>
                        </div>
                        <div class="col-6">
                            <input asp-for="EndDate" class="form-control" />
                            <span asp-validation-for="EndDate" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-4">
                            <label asp-for="Status" class="control-label"></label>
                        </div>
                        <div class="col-6">
                            <select asp-for="Status" class="form-control" asp-items="Html.GetEnumSelectList<Status>()"></select>
                            <span asp-validation-for="Status" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class=" col-3 offset-4">
                            <input type="submit" value="Create" class="btn btn-primary form-control text-white" />
                        </div>
                        <div class=" col-3 ">
                            <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

MedialCare/MedialCare/Areas/Admin/Views/PolicyOnEmployees/Delete.cshtml
@model PolicyOnEmployee

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="invoice-wrap">
    <div class="page-header">
        <h4 class="text-center mb-30 weight-600">Delete</h4>
        <p>Are you sure you want to delete this?</p>

        <div class="row pb-30">
            <div class="col-md-6">
                <h5 class="mb-15">Name Employee: <span class="font-weight-bold"> @Html.DisplayFor(model => model.User.Username)</span></h5>
                <h5 class="mb-15">Name Policy: <span class="font-weight-bold"> @Html.DisplayFor(model => model.Policy.Name)</span></h5>
                <h5 class="mb-15">Policy Amount: <span class="font-weight-bold"> @Html.DisplayFor(model => model.Policy.Amount)</span></h5>
            </div>

        </div>
        <div class="invoice-desc pb-30">
            <div class="invoice-desc-head clearfix">
                <div class="invoice-sub">Strat Date</div>
                <div class="invoice-rate">End Date</div>
                <div class="invoice-hours">Status</div>
            </div>
            <div class="invoice-desc-body">
                <ul>
                    <li class="clearfix">
                        <div class="invoice-sub">@Html.DisplayFor(model => model.StartDate)</div>
                        <div class="invoice-rate">
                            @Html.DisplayFor(model => model.EndDate)
                        </div>
                        <div class="invoice-hours">
                            @Html.DisplayFor(model => model.Status)
                        </div>
                    </li>
                </ul>
                <form asp-action="Delete">
                    <input type="hidden" asp-for="ID" />
                    <input type="submit" value="Delete" class="btn btn-danger" /> |
                    <a asp-action="Index" class="btn btn-success">Back to List</a>
                </form>
            </div>

        </div>
    </div>
</div>

MedialCare/MedialCare/Areas/Admin/Views/PolicyOnEmployees/Details.cshtml
@model PolicyOnEmployee

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="invoice-wrap">
    <div class="page-header">
        <h4 class="text-center mb-30 weight-600">Details</h4>

        <div class="row pb-30">
            <div class="col-md-6">
                <h5 class="mb-15">Name Policy: <span class="font-weight-bold"> @Html.DisplayFor(model => model.User.Username)</span></h5>
                <h5 class="mb-15">Name Policy: <span class="font-weight-bold"> @Html.DisplayFor(model => model.Policy.Name)</span></h5>
                <p class="font-14 mb-5">Policy Amount: <strong class="weight-600">@Html.DisplayFor(model => model.Policy.Amount)</strong></p>
            </div>

        </div>
        <div class="invoice-desc pb-30">
            <div class="invoice-desc-head clearfix">
                <div class="invoice-sub">Start Date</div>
                <div class="invoice-rate">End Date</div>
                <div class="invoice-hours">Status</div>
            </div>
            <div class="invoice-desc-body">
                <ul>
                    <li class="clearfix">
                        <div class="invoice-sub">@Html.DisplayFor(model => model.StartDate)</div>
                        <div class="invoice-rate">
                            @Html.DisplayFor(model => model.EndDate)
                        </div>
                        <div class="invoice-hours">
                            @Html.DisplayFor(model => model.Status)
                        </div>
                    </li>
                </ul>
                <div class="m-2">
                    <a class="btn btn-primary" asp-action="Edit" asp-route-id="@Model.ID">Edit</a>
                    <a class="btn btn-success" asp-action="Index">Back to List</a>
                </div>
            </div>

        </div>
    </div>
</div>

MedialCare/MedialCare/Areas/Admin/Views/PolicyOnEmployees/Edit.cshtml
@model PolicyOnEmployee

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="card-box">
    <h4 class="m-2">PolicyOnEmployee</h4>
    <div style="padding:30px">
        <div class="row">
            <div class="col">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger offset-4"></div>
                    <div class="form-group row">
                        <div class="col-4">

                        </div>
                        <div class="col-6">
                            <select asp-for="PolicyId" class="form-control" asp-items="ViewBag.PolicyName" hidden></select>
                            <span asp-validation-for="PolicyId" class="text-danger" ></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-4">

                        </div>
                        <div class="col-6">
                            <select asp-for="UserId" class="form-control" asp-items="ViewBag.UserName" hidden></select>
                            <span asp-validation-for="UserId" class="text-danger" ></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-4">

                        </div>
                        <div class="col-6">
                            <input asp-for="StartDate" class="form-control" type="hidden" />
                            <span asp-validation-for="StartDate" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-4">

                        </div>
                        <div class="col-6">
                            <input asp-for="EndDate" class="form-control" type="hidden" />
                            <span asp-validation-for="EndDate" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="form-group row">
                            <div class="col-4">
                                <label asp-for="Status" class="control-label"></label>
                            </div>
                            <div class="col-6">
                                <select asp-for="Status" class="form-control" asp-items="Html.GetEnumSelectList<Status>()"></select>
                                <span asp-validation-for="Status" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class=" col-3 offset-4">
                            <input type="submit" value="Edit" class="btn btn-primary form-control text-white" />
                        </div>
                        <div class=" col-3 ">
                            <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>

    </div>
</div>

MedialCare/MedialCare/Areas/Admin/Views/PolicyOnEmployees/Index.cshtml
@model ListViewModel

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="card-box pb-10">
    <div class="h5 pd-20 mb-0 ml-1">Recent Patient</div>
    <p class="ml-4">List of policy on employee</p>
    <div class="m-2 row">
        <div class="col-8">
            <a asp-area="Admin" asp-controller="PolicyOnEmployees" asp-action="Create" class="btn btn-outline-info">Create New</a>
        </div>
        <div class="header-search float-lg-right col-4">
            <form asp-action="Index">
                <div class="form-group mb-0 ">
                    <input type="text" class="form-control search-input" name="keySearch" placeholder="Search Here">
                </div>
            </form>
        </div>
    </div>
    <table class="data-table table nowrap">
        <thead>
            <tr>
                <th class="table-plus">Employee Name</th>
                <th>Policy Name</th>
                <th>Policy Amount</th>
                <th>Start Date</th>
                <th>End Date</th>
                <th>Status</th>
                <th class="datatable-nosort">Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.PolicyOnEmployee)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.User.Username)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Policy.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Policy.Amount)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StartDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EndDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    <a asp-area="Admin" asp-controller="PolicyOnEmployees" asp-action="Details" asp-route-id="@item.ID" data-color="#17a2b8" class="font-20" title="Details"><i class="icon-copy ti-eye"></i></a>
                    <a asp-area="Admin" asp-controller="PolicyOnEmployees" asp-action="Edit" asp-route-id="@item.ID" data-color="#265ed7" class="mr-2 ml-2 font-20" title="Edit"><i class="icon-copy dw dw-edit2"></i></a>
                    <a asp-area="Admin" asp-controller="PolicyOnEmployees" asp-action="Delete" asp-route-id="@item.ID" data-color="#e95959" class="font-20" title="Delete"><i class="icon-copy dw dw-delete-3"></i></a>
                </td>
            </tr>
            }

        </tbody>

    </table>
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            <div page-model="@Model.PagingModel" page-action="Index"
                 page-class="btn page-item " page-class-normal="btn-outline-dark"
                 page-classes-enabled="true" page-class-selected="  btn-info"
                 class="font-weight-bold float-lg-right  m-4">

            </div>
        </ul>
    </nav>
</div>